### ISSUE TITLE
[Bug] C++ Build error LNK2001

### ISSUE THREAD

**Issue by Kiryuumaru** [open-mmlab/mmdeploy#1906]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I am using v1.0.0rc1 before and cmake build it without any issue, I tried upgrading to latest v1.0.0rc3 and it fails

### Reproduction

Build the latest rc v1.0.0rc3 from source with:

```
cmake ..\.. -G "Visual Studio 16 2019" -T v142 -A x64 ^
        -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" ^
        -DVCPKG_INSTALL_OPTIONS="--x-abi-tools-use-exact-versions" ^
        -DVCPKG_BINARY_SOURCES="clear;files,C:/vcpkg/archives,readwrite" ^
        -DCMAKE_INSTALL_PREFIX="install" ^
        -DVCPKG_INSTALLED_DIR="C:/vcpkg/installed" ^
        -DCUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7" ^
        -DCUDNN_INCLUDE_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7/include" ^
        -DCUDNN_LIBRARY_CUDNN_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7/lib/x64/cudnn.lib" ^
        -DMMDEPLOY_BUILD_SDK="ON" ^
        -DMMDEPLOY_BUILD_SDK_CXX_API="ON" ^
        -DMMDEPLOY_BUILD_SDK_PYTHON_API="ON" ^
        -DMMDEPLOY_SHARED_LIBS="ON" ^
        -DMMDEPLOY_CODEBASES="all" ^
        -DMMDEPLOY_TARGET_BACKENDS="trt" ^
        -DMMDEPLOY_TARGET_DEVICES="cuda" ^
        -DONNXRUNTIME_DIR="C:/onnxruntime" ^
        -DONNXRUNTIME_INCLUDE_DIR="C:/onnxruntime/include" ^
        -DONNXRUNTIME_LIBRARY_ONNXRUNTIME_PATH="C:/onnxruntime/lib/onnxruntime.lib" ^
        -DTENSORRT_DIR="C:/tensorrt8.5.3.1" ^
        -DTENSORRT_INCLUDE_DIR="C:/tensorrt8.5.3.1/include" ^
        -DTENSORRT_LIBRARY_INFER="C:/tensorrt8.5.3.1/lib/nvinfer.lib" ^
        -DTENSORRT_LIBRARY_INFER_PLUGIN="C:/tensorrt8.5.3.1/lib/nvinfer_plugin.lib" ^
        -DOpenCV_DIR="C:/vcpkg/installed/x64-windows/share/opencv4" ^
        -DProtobuf_DIR="C:/vcpkg/installed/x64-windows/share/protobuf" ^
        -Dpplcv_DIR="C:/pplcv"
cmake --build . --config Release -- /m
cmake --install . --config Release
```

This exact config works with v1.0.0rc1

### Environment

```Shell
Windows 10
```

### Error traceback

```Shell
common.obj : error LNK2001: unresolved external symbol "class spdlog::logger * __cdecl mmdeploy::GetLogger(void)" (?GetLogger@mmdeploy@@YAPEAVlogger@spdlog@@XZ) [C:\mmdeploy\build\Release\csrc\mmdeploy\apis\python\mmdeploy
_python.vcxproj]
common.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl mmdeploy::StatusDomain::_do_throw_exception(class system_error2::status_code<void> const &)const " (?_do_throw_exception@StatusDomain@mmdeploy@@UEBAXAEBV?$status_code@X@system_error2@
@@Z) [C:\mmdeploy\build\Release\csrc\mmdeploy\apis\python\mmdeploy_python.vcxproj]
common.obj : error LNK2001: unresolved external symbol "public: class system_error2::status_code_domain::string_ref __cdecl mmdeploy::Status::message(void)const " (?message@Status@mmdeploy@@QEBA?AVstring_ref@status_code_domain@system_error2@@XZ) [C:\samli\viana-edge-s
ensor-teledyne\dependencies\mmdeploy\build\Release\csrc\mmdeploy\apis\python\mmdeploy_python.vcxproj]
internal.obj : error LNK2001: unresolved external symbol "public: __cdecl mmdeploy::framework::Mat::Mat(int,int,enum mmdeploy::PixelFormat,enum mmdeploy::DataType,class std::shared_ptr<void>,class mmdeploy::framework::Device)" (??0Mat@framework@mmdeploy@@QEAA@HHW4Pixe
lFormat@2@W4DataType@2@V?$shared_ptr@X@std@@VDevice@12@@Z) [C:\mmdeploy\build\Release\csrc\mmdeploy\apis\python\mmdeploy_python.vcxproj]
C:\mmdeploy\build\Release\bin\Release\mmdeploy_python.cp39-win_amd64.pyd : fatal error LNK1120: 4 unresolved externals [C:\mmdeploy\build\Release\csrc\mmdeploy\apis\python\mmde
ploy_python.vcxproj]
```

**Comment by irexyc** [comment]
I can't reproduce your problem.

Could you build sucess without `MMDEPLOY_BUILD_SDK_PYTHON_API`? 

The main difference between these two versions is in v1.0.0rc3 the default value of `MMDEPLOY_BUILD_SDK_MONOLITHIC` is set to `ON`. You could try to add `-DMMDEPLOY_BUILD_SDK_MONOLITHIC=OFF` and see if it can be success.

**Comment by Kiryuumaru** [comment]
Thank you for the fast response. After setting `-DMMDEPLOY_BUILD_SDK_MONOLITHIC=OFF` it builds successfully. After runtime I cannot load some library:

```
loading mmdeploy_execution ...
loading mmdeploy_cpu_device ...
loading mmdeploy_cuda_device ...
loading mmdeploy_graph ...
loading mmdeploy_directory_model ...
loading mmdeploy_operation ...
loading mmdeploy_operation_cpu ...
loading mmdeploy_operation_cuda ...
loading mmdeploy_operation_dummy ...
loading mmdeploy_transform ...
loading mmdeploy_transform_module ...
loading mmdeploy_trt_net ...
loading mmdeploy_net_module ...
loading mmdeploy_mmcls ...
loading mmdeploy_mmdet ...
loading mmdeploy_mmseg ...
loading mmdeploy_mmocr ...
loading mmdeploy_mmedit ...
loading mmdeploy_mmpose ...
failed to load library mmdeploy_mmpose
loading mmdeploy_mmrotate ...
loading mmdeploy_mmaction ...
```

Others seems to works well.

**Comment by irexyc** [comment]
I have no clue why mmdeploy_mmpose can't be loaded. You may use [dependencies](https://github.com/lucasg/Dependencies) to check if the dependencies of `mmdeploy_mmpose.dll` is safisfied with you environment.

**Comment by Kiryuumaru** [comment]
The opencv part is not present. I compiled the opencv using vcpkg with `"features": [ "default-features" ]`, I thought the video part is a default feature, I dont know what other specific features it requires, 
![image](https://user-images.githubusercontent.com/31558769/227440076-9d3b1f01-2e90-4cb4-8c5f-f4e2d814d1b5.png)

**Comment by irexyc** [comment]
I just download the prebuid opencv from opencv web and doesn't meet this problem. 

You may check your installed opencv folder to see is there are opencv_video4.dll or use `everything` to search on your disk. I think the issue will be resolved after adding the location of missing dll to the `path`.
